name: terraform-ci

on:
  push:
    branches: [ main ]
    paths:
      - '**.tf'
      - '.github/workflows/terraform-ci.yml'
      - 'README.md'
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/terraform-ci.yml'
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  fmt_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive
      - name: Terraform init (no backend)
        run: terraform init -backend=false
      - name: Terraform validate
        run: terraform validate -no-color
